/* IIMA Ventures — full Portfolio page data.
   Scraped from the live iimaventures.com/portfolio page (all 4 category tabs:
   Deep Tech, Digitalization, Climate Tech, Others), then cleaned: malformed/
   duplicate entries removed, company names derived from each startup's own
   domain, and logos re-processed (white background flattened to transparent,
   trimmed to their own bounding box) for a consistent look in the grid below.
   A handful of entries had no working link on the live site and are shown
   without one rather than guessing a URL. */

const PORTFOLIO_CATEGORIES = ["Deep Tech", "Digitalization", "Climate Tech", "Others"];

const PORTFOLIO_COMPANIES = [
  { name: "Agnikul Cosmos", url: "https://agnikul.in/#/", logo: "assets/portfolio-logos/062-agnikul.png", category: "Deep Tech" },
  { name: "Astroborne", url: "", logo: "assets/portfolio-logos/166-astroborne.png", category: "Deep Tech" },
  { name: "Bellatrix Aerospace", url: "https://bellatrix.aero/", logo: "assets/portfolio-logos/030-bellatrix-aerospace.png", category: "Deep Tech" },
  { name: "Chara", url: "https://chara.co.in/", logo: "assets/portfolio-logos/028-chara.png", category: "Deep Tech" },
  { name: "CogniTensor", url: "https://www.cognitensor.com/", logo: "assets/portfolio-logos/096-cognitensor.png", category: "Deep Tech" },
  { name: "Ctrl Energy", url: "https://e-trnl.energy/", logo: "assets/portfolio-logos/063-e-trnl.png", category: "Deep Tech" },
  { name: "Cynlr", url: "https://www.cynlr.com/", logo: "assets/portfolio-logos/061-cynlr.png", category: "Deep Tech" },
  { name: "Dashamlabs", url: "https://dashamlabs.com/", logo: "assets/portfolio-logos/000-dashamlabs.png", category: "Deep Tech" },
  { name: "Defect Technologies", url: "https://detecttechnologies.com/", logo: "assets/portfolio-logos/026-defect-technologies.png", category: "Deep Tech" },
  { name: "Guerin", url: "https://www.guerintech.in/", logo: "assets/portfolio-logos/024-guerintech.png", category: "Deep Tech" },
  { name: "Ivory", url: "https://www.liveivory.com/", logo: "assets/portfolio-logos/002-liveivory.png", category: "Deep Tech" },
  { name: "Mestastop Solutions", url: "https://mestastop.com/", logo: "assets/portfolio-logos/065-mestastop.png", category: "Deep Tech" },
  { name: "Metabrix", url: "https://metabrixlab.com/", logo: "assets/portfolio-logos/021-metabrixlab.png", category: "Deep Tech" },
  { name: "Minocular", url: "https://www.minocular.com/", logo: "assets/portfolio-logos/020-minocular.png", category: "Deep Tech" },
  { name: "Morphing Machines", url: "https://www.morphing.in/", logo: "assets/portfolio-logos/019-morphing.png", category: "Deep Tech" },
  { name: "Nabhdrishti", url: "https://www.nabhdrishti.in/", logo: "assets/portfolio-logos/035-nabhdrishti.png", category: "Deep Tech" },
  { name: "Orbitt Space", url: "https://www.linkedin.com/company/orbitt-space/", logo: "assets/portfolio-logos/003-linkedin.png", category: "Deep Tech" },
  { name: "Pace Robotics", url: "http://pacerobotics.net/", logo: "assets/portfolio-logos/016-pacerobotics.png", category: "Deep Tech" },
  { name: "Pixuate", url: "https://pixuate.com/", logo: "assets/portfolio-logos/014-pixuate.png", category: "Deep Tech" },
  { name: "Proeon", url: "https://proeon.co/", logo: "assets/portfolio-logos/066-proeon.png", category: "Deep Tech" },
  { name: "Quintrans", url: "https://www.quintranshyperloop.com/", logo: "assets/portfolio-logos/098-quintranshyperloop.png", category: "Deep Tech" },
  { name: "Satleo", url: "https://www.satleolabs.com/", logo: "assets/portfolio-logos/006-satleolabs.png", category: "Deep Tech" },
  { name: "The E-Plane Company", url: "https://eplane.ai/", logo: "assets/portfolio-logos/025-eplane.png", category: "Deep Tech" },
  { name: "Unbox Robotics", url: "https://unboxrobotics.com/", logo: "assets/portfolio-logos/064-unboxrobotics.png", category: "Deep Tech" },
  { name: "Vimano", url: "https://www.vimano.biz/", logo: "assets/portfolio-logos/005-vimano.png", category: "Deep Tech" },
  { name: "Zo Chai", url: "https://www.zochai.com/", logo: "assets/portfolio-logos/145-zochai.png", category: "Deep Tech" },
  { name: "vPhrase", url: "https://www.vphrase.com/", logo: "assets/portfolio-logos/060-vphrase.png", category: "Deep Tech" },
  { name: "Agrictools", url: "https://www.agrictools.com/", logo: "assets/portfolio-logos/040-agrictools.png", category: "Digitalization" },
  { name: "Anniyam", url: "https://www.anniyam.com/", logo: "assets/portfolio-logos/044-anniyam.png", category: "Digitalization" },
  { name: "Arboreum", url: "https://www.arboreum.dev/", logo: "assets/portfolio-logos/161-arboreum.png", category: "Digitalization" },
  { name: "Awaaz", url: "http://awaaz.de/", logo: "assets/portfolio-logos/093-awaaz.png", category: "Digitalization" },
  { name: "Bridge2capital", url: "https://www.bridge2capital.com/", logo: "assets/portfolio-logos/092-bridge2capital.png", category: "Digitalization" },
  { name: "Chitmonks", url: "https://chitmonks.com/", logo: "assets/portfolio-logos/091-chitmonks.png", category: "Digitalization" },
  { name: "Credochain", url: "https://credochain.com/", logo: "assets/portfolio-logos/080-credochain.png", category: "Digitalization" },
  { name: "Culture Circle", url: "https://www.culture-circle.com/", logo: "assets/portfolio-logos/027-culture-circle.png", category: "Digitalization" },
  { name: "Curelohealth", url: "https://curelohealth.com/", logo: "assets/portfolio-logos/039-curelohealth.png", category: "Digitalization" },
  { name: "Entitled", url: "https://www.entitled.co.in/", logo: "assets/portfolio-logos/081-entitled.png", category: "Digitalization" },
  { name: "Eternz", url: "https://www.eternz.com/", logo: "assets/portfolio-logos/036-eternz.png", category: "Digitalization" },
  { name: "Fello", url: "https://fello.in/", logo: "assets/portfolio-logos/074-fello.png", category: "Digitalization" },
  { name: "Finarkein", url: "https://finarkein.com/", logo: "assets/portfolio-logos/084-finarkein.png", category: "Digitalization" },
  { name: "Finequs", url: "https://finequs.com/", logo: "assets/portfolio-logos/045-finequs.png", category: "Digitalization" },
  { name: "Flyk", url: "https://www.flyk.in/", logo: "assets/portfolio-logos/086-flyk.png", category: "Digitalization" },
  { name: "Frontier Markets", url: "https://www.frontiermkts.com/", logo: "assets/portfolio-logos/076-frontiermkts.png", category: "Digitalization" },
  { name: "Fundfina", url: "https://www.fundfina.com/", logo: "assets/portfolio-logos/082-fundfina.png", category: "Digitalization" },
  { name: "Gogullak", url: "https://gogullak.com/", logo: "assets/portfolio-logos/162-gogullak.png", category: "Digitalization" },
  { name: "Gramcover", url: "https://www.gramcover.com/", logo: "assets/portfolio-logos/073-gramcover.png", category: "Digitalization" },
  { name: "Inovec", url: "https://www.inovec.in/", logo: "assets/portfolio-logos/049-inovec.png", category: "Digitalization" },
  { name: "JAI Kisan", url: "https://www.jai-kisan.com/", logo: "assets/portfolio-logos/072-jai-kisan.png", category: "Digitalization" },
  { name: "Jigyasarurban", url: "https://jigyasarurban.com/", logo: "assets/portfolio-logos/048-jigyasarurban.png", category: "Digitalization" },
  { name: "Kaarigarmandi", url: "https://kaarigarmandi.in/", logo: "assets/portfolio-logos/043-kaarigarmandi.png", category: "Digitalization" },
  { name: "Kaleidofin", url: "https://kaleidofin.com/", logo: "assets/portfolio-logos/068-kaleidofin.png", category: "Digitalization" },
  { name: "Kniru", url: "https://www.kniru.com/", logo: "assets/portfolio-logos/041-kniru.png", category: "Digitalization" },
  { name: "Kosh", url: "https://getkosh.com/", logo: "assets/portfolio-logos/075-getkosh.png", category: "Digitalization" },
  { name: "Loanwiser", url: "https://www.loanwiser.in", logo: "assets/portfolio-logos/124-loanwiser.png", category: "Digitalization" },
  { name: "Lumovhealth", url: "https://www.lumovhealth.com/", logo: "assets/portfolio-logos/001-lumovhealth.png", category: "Digitalization" },
  { name: "Makspay", url: "https://www.makspay.com/", logo: "assets/portfolio-logos/047-makspay.png", category: "Digitalization" },
  { name: "Microfinance", url: "http://microfinance.ai/", logo: "assets/portfolio-logos/094-microfinance.png", category: "Digitalization" },
  { name: "Mimoiq", url: "https://mimoiq.com/", logo: "assets/portfolio-logos/088-mimoiq.png", category: "Digitalization" },
  { name: "Mool", url: "https://www.mool.one/", logo: "assets/portfolio-logos/097-mool.png", category: "Digitalization" },
  { name: "Mymobiforce", url: "https://mymobiforce.com/", logo: "assets/portfolio-logos/069-mymobiforce.png", category: "Digitalization" },
  { name: "Mypaisaa", url: "https://www.mypaisaa.com/", logo: "assets/portfolio-logos/079-mypaisaa.png", category: "Digitalization" },
  { name: "Mypaymart", url: "http://mypaymart.com/", logo: "assets/portfolio-logos/090-mypaymart.png", category: "Digitalization" },
  { name: "Navanc", url: "https://www.navanc.com/", logo: "assets/portfolio-logos/007-navanc.png", category: "Digitalization" },
  { name: "Nprep", url: "https://admin.nprep.in/", logo: "assets/portfolio-logos/018-admin.png", category: "Digitalization" },
  { name: "Payagri", url: "https://www.payagri.com/", logo: "assets/portfolio-logos/077-payagri.png", category: "Digitalization" },
  { name: "Payyd", url: "https://payyd.money/", logo: "assets/portfolio-logos/034-payyd.png", category: "Digitalization" },
  { name: "Reslink Logo Black", url: "", logo: "assets/portfolio-logos/167-reslink-logo-black.png", category: "Digitalization" },
  { name: "Riskcovry", url: "https://riskcovry.com/", logo: "assets/portfolio-logos/070-riskcovry.png", category: "Digitalization" },
  { name: "Roopya", url: "https://roopya.money/", logo: "assets/portfolio-logos/046-roopya.png", category: "Digitalization" },
  { name: "SarvDhan", url: "https://sarvdhan.com/en", logo: "assets/portfolio-logos/011-sarvdhan.png", category: "Digitalization" },
  { name: "Setu", url: "https://setu.co/", logo: "assets/portfolio-logos/067-setu.png", category: "Digitalization" },
  { name: "Superzop", url: "https://www.superzop.com/", logo: "assets/portfolio-logos/071-superzop.png", category: "Digitalization" },
  { name: "Tarrakki", url: "https://www.tarrakki.com/", logo: "assets/portfolio-logos/042-tarrakki.png", category: "Digitalization" },
  { name: "Tpsqonect", url: "https://www.tpsqonect.com/", logo: "assets/portfolio-logos/083-tpsqonect.png", category: "Digitalization" },
  { name: "Upaz", url: "https://www.upaz.in/", logo: "assets/portfolio-logos/078-upaz.png", category: "Digitalization" },
  { name: "WHR", url: "https://www.whr.loans/", logo: "assets/portfolio-logos/160-whr.png", category: "Digitalization" },
  { name: "Xemi", url: "https://www.xemi.io/", logo: "assets/portfolio-logos/038-xemi.png", category: "Digitalization" },
  { name: "Amplepac", url: "http://amplepac.com/", logo: "assets/portfolio-logos/057-amplepac.png", category: "Climate Tech" },
  { name: "Angirusind", url: "https://www.angirusind.com/", logo: "assets/portfolio-logos/135-angirusind.png", category: "Climate Tech" },
  { name: "Bizlog", url: "https://bizlog.in/", logo: "assets/portfolio-logos/056-bizlog.png", category: "Climate Tech" },
  { name: "Brisil", url: "", logo: "assets/portfolio-logos/165-brisil.png", category: "Climate Tech" },
  { name: "Carbontrail", url: "https://carbontrail.net/", logo: "assets/portfolio-logos/029-carbontrail.png", category: "Climate Tech" },
  { name: "Cellpropulsion", url: "http://www.cellpropulsion.com/home.html", logo: "assets/portfolio-logos/055-cellpropulsion.png", category: "Climate Tech" },
  { name: "Cleanelectric", url: "https://www.cleanelectric.in/", logo: "assets/portfolio-logos/147-cleanelectric.png", category: "Climate Tech" },
  { name: "Ecoratings", url: "", logo: "assets/portfolio-logos/164-ecoratings.png", category: "Climate Tech" },
  { name: "Fluidrobotics", url: "https://www.fluidrobotics.com/", logo: "assets/portfolio-logos/059-fluidrobotics.png", category: "Climate Tech" },
  { name: "Nunam", url: "https://nunam.com/", logo: "assets/portfolio-logos/017-nunam.png", category: "Climate Tech" },
  { name: "Onnes Aerospace", url: "https://onnes.in/", logo: "assets/portfolio-logos/004-onnes.png", category: "Climate Tech" },
  { name: "Regrip", url: "http://regrip.in/", logo: "assets/portfolio-logos/136-regrip.png", category: "Climate Tech" },
  { name: "Renkube", url: "https://www.renkube.com/", logo: "assets/portfolio-logos/053-renkube.png", category: "Climate Tech" },
  { name: "Sentra", url: "https://sentra.world/", logo: "assets/portfolio-logos/010-sentra.png", category: "Climate Tech" },
  { name: "Sustlabs", url: "https://www.sustlabs.com/", logo: "assets/portfolio-logos/008-sustlabs.png", category: "Climate Tech" },
  { name: "Tan90thermal", url: "https://www.tan90thermal.com/", logo: "assets/portfolio-logos/058-tan90thermal.png", category: "Climate Tech" },
  { name: "Taqanal", url: "https://www.taqanal.com/", logo: "assets/portfolio-logos/095-taqanal.png", category: "Climate Tech" },
  { name: "Thedisposalcompany", url: "http://www.thedisposalcompany.com/", logo: "assets/portfolio-logos/054-thedisposalcompany.png", category: "Climate Tech" },
  { name: "256bitsstudio", url: "https://www.256bitsstudio.com/", logo: "assets/portfolio-logos/033-256bitsstudio.png", category: "Others" },
  { name: "Abiracreations", url: "https://www.abiracreations.com", logo: "assets/portfolio-logos/112-abiracreations.png", category: "Others" },
  { name: "Aggio", url: "https://www.aggio.io/", logo: "assets/portfolio-logos/089-aggio.png", category: "Others" },
  { name: "Agrograde", url: "https://agrograde.com/", logo: "assets/portfolio-logos/146-agrograde.png", category: "Others" },
  { name: "Amounee", url: "https://amounee.com/?v=4cd05540c260", logo: "assets/portfolio-logos/126-amounee.png", category: "Others" },
  { name: "Amritatva", url: "https://amritatva.com/", logo: "assets/portfolio-logos/134-amritatva.png", category: "Others" },
  { name: "Aoki", url: "https://aoki.co.in/", logo: "assets/portfolio-logos/031-aoki.png", category: "Others" },
  { name: "Apnagodam", url: "http://apnagodam.com/", logo: "assets/portfolio-logos/107-apnagodam.png", category: "Others" },
  { name: "Avidialabs", url: "https://avidialabs.com/", logo: "assets/portfolio-logos/143-avidialabs.png", category: "Others" },
  { name: "Baansuli", url: "https://baansuli.com/site/", logo: "assets/portfolio-logos/139-baansuli.png", category: "Others" },
  { name: "Balwaan", url: "https://www.balwaan.com/", logo: "assets/portfolio-logos/114-balwaan.png", category: "Others" },
  { name: "Bebefoods", url: "http://bebefoods.com/", logo: "assets/portfolio-logos/110-bebefoods.png", category: "Others" },
  { name: "Bharatrohan", url: "https://www.bharatrohan.in", logo: "assets/portfolio-logos/119-bharatrohan.png", category: "Others" },
  { name: "Blackboardradio", url: "https://www.blackboardradio.com/", logo: "assets/portfolio-logos/052-blackboardradio.png", category: "Others" },
  { name: "Bookmybai", url: "https://www.bookmybai.com/", logo: "assets/portfolio-logos/117-bookmybai.png", category: "Others" },
  { name: "Braingroom", url: "https://www.braingroom.com/", logo: "assets/portfolio-logos/148-braingroom.png", category: "Others" },
  { name: "Butterflylearnings", url: "https://www.butterflylearnings.com/", logo: "assets/portfolio-logos/099-butterflylearnings.png", category: "Others" },
  { name: "Camelcharisma", url: "https://www.camelcharisma.com/", logo: "assets/portfolio-logos/109-camelcharisma.png", category: "Others" },
  { name: "Carmelorganics", url: "http://www.carmelorganics.in/", logo: "assets/portfolio-logos/100-carmelorganics.png", category: "Others" },
  { name: "Cattlemettle", url: "http://www.cattlemettle.com/", logo: "assets/portfolio-logos/101-cattlemettle.png", category: "Others" },
  { name: "Comofimedtech", url: "https://www.comofimedtech.com/", logo: "assets/portfolio-logos/085-comofimedtech.png", category: "Others" },
  { name: "Contree", url: "http://www.contree.in/", logo: "assets/portfolio-logos/105-contree.png", category: "Others" },
  { name: "Cottonrack", url: "https://cottonrack.com/", logo: "assets/portfolio-logos/118-cottonrack.png", category: "Others" },
  { name: "Cretile", url: "https://www.cretile.com/", logo: "assets/portfolio-logos/149-cretile.png", category: "Others" },
  { name: "Crooze", url: "https://crooze.app/", logo: "assets/portfolio-logos/158-crooze.png", category: "Others" },
  { name: "Desigomilk", url: "https://www.desigomilk.com", logo: "assets/portfolio-logos/115-desigomilk.png", category: "Others" },
  { name: "Desihangover", url: "https://www.desihangover.in/", logo: "assets/portfolio-logos/132-desihangover.png", category: "Others" },
  { name: "Dressfolk", url: "https://dressfolk.com/", logo: "assets/portfolio-logos/123-dressfolk.png", category: "Others" },
  { name: "Fabriclore", url: "https://fabriclore.com/", logo: "assets/portfolio-logos/120-fabriclore.png", category: "Others" },
  { name: "Fabricmonde", url: "http://www.fabricmonde.com/", logo: "assets/portfolio-logos/111-fabricmonde.png", category: "Others" },
  { name: "GUVI", url: "https://www.guvi.in/", logo: "assets/portfolio-logos/087-guvi.png", category: "Others" },
  { name: "Geekster", url: "https://www.geekster.in/", logo: "assets/portfolio-logos/050-geekster.png", category: "Others" },
  { name: "Getamply", url: "https://www.getamply.co/", logo: "assets/portfolio-logos/032-getamply.png", category: "Others" },
  { name: "Godaam Innovations", url: "", logo: "assets/portfolio-logos/163-godaam-innovations.png", category: "Others" },
  { name: "Gramshree", url: "http://www.gramshree.net/", logo: "assets/portfolio-logos/108-gramshree.png", category: "Others" },
  { name: "Greenday", url: "https://greenday.co/", logo: "assets/portfolio-logos/154-greenday.png", category: "Others" },
  { name: "Greenikk", url: "https://greenikk.com/", logo: "assets/portfolio-logos/156-greenikk.png", category: "Others" },
  { name: "Guddee", url: "https://www.guddee.in/", logo: "assets/portfolio-logos/138-guddee.png", category: "Others" },
  { name: "Guitaa", url: "https://guitaa.com/", logo: "assets/portfolio-logos/144-guitaa.png", category: "Others" },
  { name: "Innofarms", url: "http://innofarms.co.in/", logo: "assets/portfolio-logos/142-innofarms.png", category: "Others" },
  { name: "Kalagharstore", url: "https://www.kalagharstore.com/", logo: "assets/portfolio-logos/116-kalagharstore.png", category: "Others" },
  { name: "Karghewale", url: "https://karghewale.com/", logo: "assets/portfolio-logos/159-karghewale.png", category: "Others" },
  { name: "Katori", url: "https://katori.co.in/", logo: "assets/portfolio-logos/113-katori.png", category: "Others" },
  { name: "Kaushalbhaav", url: "http://www.kaushalbhaav.com/", logo: "assets/portfolio-logos/104-kaushalbhaav.png", category: "Others" },
  { name: "Kaushalcircle", url: "https://kaushalcircle.com/", logo: "assets/portfolio-logos/152-kaushalcircle.png", category: "Others" },
  { name: "Khadigi", url: "http://khadigi.co.in/", logo: "assets/portfolio-logos/102-khadigi.png", category: "Others" },
  { name: "Kidaura", url: "https://kidaura.in/", logo: "assets/portfolio-logos/023-kidaura.png", category: "Others" },
  { name: "Kineerblessed", url: "https://www.kineerblessed.com/", logo: "assets/portfolio-logos/121-kineerblessed.png", category: "Others" },
  { name: "Knowlens", url: "https://www.knowlens.com/", logo: "assets/portfolio-logos/150-knowlens.png", category: "Others" },
  { name: "Knparises", url: "https://www.knparises.com/", logo: "assets/portfolio-logos/130-knparises.png", category: "Others" },
  { name: "Konkuwanherbs", url: "https://www.konkuwanherbs.com/", logo: "assets/portfolio-logos/157-konkuwanherbs.png", category: "Others" },
  { name: "Kosha", url: "https://www.kosha.ai/", logo: "assets/portfolio-logos/131-kosha.png", category: "Others" },
  { name: "Kriyalabs", url: "http://www.kriyalabs.co.in/", logo: "assets/portfolio-logos/122-kriyalabs.png", category: "Others" },
  { name: "Languify", url: "https://languify.in/", logo: "assets/portfolio-logos/129-languify.png", category: "Others" },
  { name: "Lares", url: "https://www.lares.ai/", logo: "assets/portfolio-logos/022-lares.png", category: "Others" },
  { name: "Mediengg", url: "http://www.mediengg.com/", logo: "assets/portfolio-logos/106-mediengg.png", category: "Others" },
  { name: "Memeraki", url: "https://www.memeraki.com/", logo: "assets/portfolio-logos/155-memeraki.png", category: "Others" },
  { name: "Multibhashi", url: "http://www.multibhashi.com/", logo: "assets/portfolio-logos/103-multibhashi.png", category: "Others" },
  { name: "Myways", url: "https://www.myways.in/", logo: "assets/portfolio-logos/151-myways.png", category: "Others" },
  { name: "Neerx", url: "https://www.neerx.in", logo: "assets/portfolio-logos/127-neerx.png", category: "Others" },
  { name: "Pacifymedical", url: "https://pacifymedical.com/", logo: "assets/portfolio-logos/015-pacifymedical.png", category: "Others" },
  { name: "Protrainy", url: "https://protrainy.com/", logo: "assets/portfolio-logos/137-protrainy.png", category: "Others" },
  { name: "Qlan", url: "https://qlan.gg/", logo: "assets/portfolio-logos/051-qlan.png", category: "Others" },
  { name: "Rashki", url: "https://rashki.com/", logo: "assets/portfolio-logos/141-rashki.png", category: "Others" },
  { name: "Redicinemedsol", url: "https://www.redicinemedsol.com/", logo: "assets/portfolio-logos/013-redicinemedsol.png", category: "Others" },
  { name: "Revidd", url: "https://www.revidd.com/", logo: "assets/portfolio-logos/012-revidd.png", category: "Others" },
  { name: "Shoegaro", url: "https://shoegaro.in/", logo: "assets/portfolio-logos/153-shoegaro.png", category: "Others" },
  { name: "Sova", url: "https://www.sova.health/?srsltid=AfmBOop2yLM4e2BcV2ZFUDiFLUeBwUyaAfTwsxCVu6k1hZEn3J2b-1oV", logo: "assets/portfolio-logos/009-sova.png", category: "Others" },
  { name: "Sunokitaab", url: "https://sunokitaab.com/", logo: "assets/portfolio-logos/133-sunokitaab.png", category: "Others" },
  { name: "Urbankhet", url: "https://www.urbankhet.biz/", logo: "assets/portfolio-logos/128-urbankhet.png", category: "Others" },
  { name: "Verthbox", url: "https://www.verthbox.com/", logo: "assets/portfolio-logos/140-verthbox.png", category: "Others" },
  { name: "Wideneed", url: "http://wideneed.com/peeschute/", logo: "assets/portfolio-logos/125-wideneed.png", category: "Others" },
  { name: "Yourbasil", url: "https://yourbasil.com", logo: "assets/portfolio-logos/037-yourbasil.png", category: "Others" },
];
